### ISSUE TITLE
添加的 VNote 笔记本无法显示

### ISSUE THREAD

**Issue by HaujetZhao** [vnotex/viki#15]
如下例子

站点文件在 [https://gitee.com/haujet/MyVikiBook/tree/master/dist](https://gitee.com/haujet/MyVikiBook/tree/master/dist)

![image](https://user-images.githubusercontent.com/19181833/85148894-40739d00-b283-11ea-9824-7d84b91694f0.png)

托管在 [https://haujet.gitee.io/myvikibook/#](https://haujet.gitee.io/myvikibook/#)

![image](https://user-images.githubusercontent.com/19181833/85148930-4c5f5f00-b283-11ea-9096-5d98c380b99c.png)

这是 navigation.json 的内容：

![image](https://user-images.githubusercontent.com/19181833/85149763-44ec8580-b284-11ea-92f8-ee5713b7e29a.png)

但是在 [https://haujet.gitee.io/myvikibook/#!测试笔记本/_vnote.json](https://haujet.gitee.io/myvikibook/#!测试笔记本/_vnote.json) 页面下为空白：

![image](https://user-images.githubusercontent.com/19181833/85149291-b24be680-b283-11ea-970b-f81054eb6a9a.png)

VNote 笔记本内的内容无法显示。

**Comment by tamlok** [comment]
按f12看一下有啥出错信息

**Comment by HaujetZhao** [comment]
> 按f12看一下有啥出错信息

在本地试了下

错误信息：

![image](https://user-images.githubusercontent.com/19181833/85188376-8c046600-b2d8-11ea-9b16-77d2da38d827.png)

是 `http://127.0.0.1/MyVikiBook/dist/index.html%E6%B5%8B%E8%AF%95%E7%AC%94%E8%AE%B0%E6%9C%AC/_vnote.json?id=%23&path=%E6%B5%8B%E8%AF%95%E7%AC%94%E8%AE%B0%E6%9C%AC` 出了404

转义后是 `127.0.0.1/MyVikiBook/dist/index.html测试笔记本/_vnote.json?id=%23&path=测试笔记本` 出了404，但这个链接形式应该不对吧

**Comment by HaujetZhao** [comment]
明白了。我是以 `http://127.0.0.1/MyVikiBook/dist/index.html` 的形式打开 Viki 的，所以打开笔记本的时候，Viki 生成了 `http://127.0.0.1/MyVikiBook/dist/index.html测试笔记本/_vnote.json` 这样的链接。

当我用  `http://127.0.0.1/MyVikiBook/dist` 的形式打开 Viki ，没有加 `index.html`，那么在打开笔记本的时候，Viki 生成的就是 `http://127.0.0.1/MyVikiBook/dist/index.html测试笔记本/_vnote.json` 这样的链接。

不知道能不能修复这个问题呢？

**Comment by HaujetZhao** [comment]
另外，gitee 托管的页面，无法访问以下滑线开头的资源，例如 "_vnote.json"，在其 pages 上托管的 viki 也就无法打开笔记本了。

如果将   "_vnote.json" 改成  "vnote.json" ，那 viki 就不认它为一个笔记本了。

@tamlok

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/85188928-e56e9400-b2dc-11ea-992e-5463150e3d99.png)

**Comment by HaujetZhao** [comment]
非常感谢！是我的疏忽，没认真找到这个方法。
