### ISSUE TITLE
怎么设置默认展开第一层目录呢？

### ISSUE THREAD

**Issue by empty-id** [vnotex/viki#21]
如果目录多的话每次都要一个个点开，有些麻烦。

**Comment by null-id** [comment]
其实vnote也有这个问题

**Comment by null-id** [comment]
@rcocco 不好意思又打扰您了，我不太懂js，可以麻烦帮忙看一下吗？谢谢！

**Comment by tamlok** [comment]
Hi,

已经支持： https://github.com/vnotex/viki/releases/tag/v3.2.0

具体参考`navigation.json`里面的配置。
