### ISSUE TITLE
相对路径的图片无法显示

### ISSUE THREAD

**Issue by null-id** [vnotex/viki#26]
vnote 3.0笔记里面用相对路径表示的图片无法在viki里面显示。

**Comment by tamlok** [comment]
给具体例子呀

**Comment by null-id** [comment]
[例子](https://null-id.github.io/viki/#!机器学习/课程笔记/cs229：机器学习.md#toc_1)

**Comment by null-id** [comment]
[例子](https://null-id.github.io/viki/#!机器学习/课程笔记/cs229：机器学习.md)

**Comment by tamlok** [comment]
https://tamlok.gitee.io/viki/zh_cn/#!get_started.md

```
你需要在项目根目录下添加一个.nojekyll文件，以关闭Jekyll服务。否则，任何以下划线开始命名的文件和目录都会被过滤掉。具体参考 GitHub Blogs 。
```

**Comment by null-id** [comment]
确实可以了，感谢！
